### ISSUE TITLE
Empty word with high count when using pretrained vectors

### ISSUE THREAD

**Issue by gartentrio** [tshev/faster-FastText#5]
Moving a word in getInputMatrixFromFile() and then adding it to the dictionary leads to an empty word with count of vocabulary size.
```
std::string word;
in >> word;
words.push_back(std::move(word));
dict_->add(word);
```

**Comment by tshev** [comment]
Thank you. Good catch.

**Comment by tshev** [comment]
Fixed: https://github.com/tshev/faster-FastText/pull/6
